name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer
        # Sahi repository name aur version
        uses: ArtemSerebrennkov/buildozer-action@v1.6.1
        with:
          workdir: .
          buildozer_version: master

      - name: Upload APK
        # Naya version v4 jo GitHub mang raha hai
        uses: actions/upload-artifact@v4
        with:
          name: PoolHelper-APK
          path: bin/*.apk
